config/routes.rb
Rails.application.routes.draw do    

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    get 'fast_registrations', to: 'fast_registrations#show', as: :show_fast_registrations
    post 'fast_registrations', to: 'fast_registrations#quick_registration', as: :fast_registration

  end
    
  scope "(:locale)", locale: /en|ru/ do  
    resources :orders
    resources :carts, only: [:show, :update]
    resources :line_items
    resources :catalog, only: [:index, :show]
    resources :checkouts, only: [:show, :update]
    resources :books do
      post :create_line_item, on: :member
    end
    resource :user, only: [:edit] do 
      collection do 
        patch 'update_password'
        patch 'update_email'
      end
    end
    get '/users/:id', to: 'users#settings', as: 'settings'
    patch 'users/:id', to: 'users#update_address', as:'update_address'
    root to:"home#index"
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook] #, :confirmable
  has_many :orders, dependent: :destroy
  
  has_one :shipping_address, as: :addressable, dependent: :destroy
  has_one :billing_address, as: :addressable, dependent: :destroy
  validates :email, :password, presence: true
  validates :email, format: {with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/iu }
  #validates :password, format: {with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}\z/}
  #has_one :avatar, as: :imageable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      name = auth.info.name.split(' ')
      user.create_billing_address(first_name: name[0],last_name: name[1])
      user.create_shipping_address(first_name: name[0],last_name: name[1])
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


  def self.fast_registration(sign_up_params)
    user = new sign_up_params
    user.provider = 'fast'
    user.password = Devise.friendly_token[0,20]
    ApplicationMailer.send_password(user.email, user.password).deliver_now if user.save
    user
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Rectify::ControllerHelpers
  before_action :authenticate_user!
  before_action :set_countries
 
  def settings
    present AddressesPresenter.new
  end

  def update_address
    UpdateAddress.call(params, current_user) do
      on(:ok) do 
        success
      end
      on(:invalid) do |*attrs|        
        present AddressesPresenter.new(*attrs)
        render 'settings'
      end      
    end
  end

  def update_email
  @user = current_user
    if @user.update(user_params)
       success
    else
      error
    end
  end

  def update_password
    @user = current_user
    if @user.update_with_password(user_params)
      bypass_sign_in(@user)
      success
    else
      error
    end
  end

private
  

  def set_countries
    @countries = Country.select(:id, :name)
  end

  def user_params
    params.require(:user).permit(:email, :current_password, :password, :confirm_password)
  end

  def success
    redirect_to settings_path(current_user), notice: 'info successfuly updated'
  end

  def error
    present AddressesPresenter.new      
    render action: 'settings'
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_address_form.html.haml
= simple_form_for current_user, url: update_address_path(current_user) do |f|
  =f.simple_fields_for type, object do |item_field|
    =render 'fields', field: item_field
    .mb-40
      .text-center.general-text-align
        = f.button :submit, class: "btn btn-default mb-35"

app/views/users/_change_email.html.haml
=simple_form_for current_user, url: { action: "update_email", anchor: 'privacy' }, method: :patch, class: 'general-form-md' do |f|
  .form-group.mb-35
    =f.input :email, placeholder: "Enter your email", class: 'form-control', id: 'email'
  .general-text-align
    =f.button :submit, class: 'btn btn-default mb-35'

app/views/users/_change_password.html.haml
=simple_form_for current_user, url: { action: "update_password" }, method: :patch, class: 'general-form-md' do |f|
  .form-group.mb-30
    =f.input :current_password, placeholder: "Current Password", class: 'form-control', id: 'oldPassword'
  .form-group.mb-30
    =f.input :password, placeholder: "New Password", class: 'form-control', id: 'password'
  .form-group.mb-40
    =f.input :password_confirmation, placeholder: "Confirm Password", class: 'form-control', id: 'confirmPassword'
  .general-text-align
    =f.button :submit, class: 'btn btn-default mb-35'

app/views/users/_fields.html.haml
-[:first_name, :last_name, :address, :city, :zip].each do |string|
  .form-group
    =field.input string, id: "#{string}"
.form-group
  =field.input :country_id, collection: @countries,  id: 'country',  placeholder: "Select a country"
.form-group.mb-60
  =field.input :phone, id: "phone", type: "tel", placeholder: "Example +3556614567"

app/views/users/_remove_account.html.haml
= simple_form_for current_user, url: user_registration_path, method: :delete, id: 'destroy_account' do |f|

  .general-settings-btn
    = f.submit 'Please Remove My Account', class: 'btn btn-default mb-20'
  .form-group.checkbox.general-settings-checkbox
    %label.checkbox-label
      = check_box_tag :agree_cancel, 0, false, class: 'checkbox-input',
        hidden: 'hidden'
      %span.checkbox-icon
        %i.fa.fa-check
      %span.checkbox-text I understand that all data will be lost

app/views/users/settings.html.haml
%main.container
  %h1.general-title-margin= t('.settings_title')
  %ul.nav.nav-tabs.mb-20{role: "tablist"}
    %li.mb-10.active{role: "presentation"}
      %a{href: "#address", 'aria-controls': "address", role: "tab", 'data-toggle': "tab"} Address
    %li.mb-10{role: "presentation"}
      %a{href: "#privacy", 'aria-controls': "privacy", role: "tab", 'data-toggle': "tab"} Privacy
  .tab-content
    #address.tab-pane.fade.in.active{role: "tabpanel"}
      .general-main-wrap
        .hidden-xs.hidden-sm
          .row
            .col-md-5
              %h3.general-subtitle.mt-0 Billing Address
            .col-md-5.col-md-offset-1
              %h3.general-subtitle.mt-0 Shipping Address
        .row
          .col-md-5.mb-40
            .visible-xs.visible-sm
              %h3.general-subtitle.mt-0 Billing Address
            =render 'address_form', object: presenter.billing, type: :billing
          .col-md-5.mb-40.col-md-offset-1.mb-25
            .visible-xs.visible-sm
              %h3.general-subtitle.mt-0 Shipping Address
            =render 'address_form', object: presenter.shipping, type: :shipping
    -unless current_user.provider
      #privacy.tab-pane.fade{role: "tabpanel"}
        .row.mb-60
          .col-sm-5
            %p.in-gold-500.font-18.mb-25 Email
            = render 'change_email'
          .col-sm-5.col-sm-offset-1
            %p.in-gold-500.font-18.mb-25 Password
            = render 'change_password'
          .col-sm-12
            .divider-lg-bottom
            %p.in-gold-500.font-18.mb-25 Remove Account
            = render 'remove_account'