config/routes.rb
Rails.application.routes.draw do    

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    get 'fast_registrations', to: 'fast_registrations#show', as: :show_fast_registrations
    post 'fast_registrations', to: 'fast_registrations#quick_registration', as: :fast_registration

  end
    
  scope "(:locale)", locale: /en|ru/ do  
    resources :orders
    resources :carts, only: [:show, :update]
    resources :line_items
    resources :catalog, only: [:index, :show]
    resources :checkouts, only: [:show, :update]
    resources :books do
      post :create_line_item, on: :member
    end
    resource :user, only: [:edit] do 
      collection do 
        patch 'update_password'
        patch 'update_email'
      end
    end
    get '/users/:id', to: 'users#settings', as: 'settings'
    patch 'users/:id', to: 'users#update_address', as:'update_address'
    root to:"home#index"
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include Rectify::ControllerHelpers
 
  def show
    present OrderSummaryPresenter.new(order: @order)
  end

  def update
    UpdateCart.call(params, @order) do
      on(:update_cart) { redirect_to cart_path(id: session[:order_id]),  notice: 'Cart was successfuly updated!' }
      on(:to_checkout) {redirect_to checkout_path(:address)}
      on(:invalid) {|*attrs| redirect_to cart_path(@order),  alert: "#{@form.errors.full_messages}"
       }
    end    
  end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_line_item.html.haml
%tr
  %td
    .general-img-wrap-table
      =image_tag line_item.book.main_picture
  %td
    %p.general-title 
      =line_item.book.title
  %td
    %span.font-16.in-gold-500 
      =number_to_currency(line_item.book.price)
  %td
    %span.font-16.in-gold-500 
      .input-group
        - if local_assigns[:field]
          %div.input-link
            %i.glyphicon.glyphicon-minus.line-height-40{type: 'button', onclick: "decrementVal()"}
          =field.text_field :quantity, value: line_item.quantity, class: 'form-control quantity-input', id: 'form_quantity'
          %div.input-link
            %i.glyphicon.glyphicon-plus.line-height-40{type: 'button', onclick: "incrementVal()"}
        -else
          =line_item.quantity
  %td
    %span.font-16.in-gold-500 
      =number_to_currency(line_item.total_price)
  - if local_assigns[:field]
    %td
      =link_to line_item_path(line_item), method: :delete, class: 'close general-cart-close' do    
        %span{'aria-hidden': "true"} &times;

app/views/carts/_table.html.haml
%table.table.table-hover
  %thead
    %tr
      %th
        %span.in-grey-600= t('carts.show.product')
      %th.col-title
      %th.col-price
        %span.in-grey-600= t('carts.show.price')
      %th
        %span.in-grey-600= t('carts.show.quantity')
      %th
        %span.in-grey-600= t('carts.show.sub_total')      
        %th.close-link
  %tbody
    - if local_assigns[:field]  
      = field.simple_fields_for :line_items do |line|
        = render 'line_item', line_item: line.object,
            field: line
    -else
      -line_items.each do |line|
        = render 'carts/line_item', line_item: line

app/views/carts/index.html.haml
<!DOCTYPE html>
%html
  %head
    %meta{charset: "UTF-8"}
    %meta{name: "viewport", content: "width=device-width"}
    %title Bookstore
    %link{href: "https://fonts.googleapis.com/css?family=Open+Sans:300,400,600", rel: "stylesheet"}
    %link{href: "../css/style.css", rel: "stylesheet"}
  %body    
    %main.container.general-main-wrap
      %h1.general-title-margin Cart
      .visible-xs
        .general-cart-item.divider-lg-bottom
          %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
            %span{'aria-hidden': "true"} &times;
          .general-img-wrap-table
            %img.cart-img-shadow{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
          %p.general-title Android Programming for Beginners
          %table.table
            %tr
              %td
                %span.in-grey-600 Price
              %td
                %span.font-16.in-gold-500 €28.50
            %tr
              %td.vertical-middle
                %span.in-grey-600 Quantity
              %td
                .input-group
                  %a.input-link{href: "#"}
                    %i.fa.fa-minus.line-height-40
                  %input.form-control.quantity-input{type: "text"}
                  %a.input-link{href: "#"}
                    %i.fa.fa-plus.line-height-40
            %tr
              %td
                %span.in-grey-600 SubTotal
              %td
                %span.font-16.in-gold-500 €32.90
        .general-cart-item.divider-lg-bottom.mb-30
          %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
            %span{'aria-hidden': "true"} &times;
          .general-img-wrap-table
            %img.cart-img-shadow{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
          %p.general-title Android Programming for Beginners
          %table.table
            %tr
              %td
                %span.in-grey-600 Price
              %td
                %span.font-16.in-gold-500 €28.50
            %tr
              %td.vertical-middle
                %span.in-grey-600 Quantity
              %td
                .input-group
                  %a.input-link{href: "#"}
                    %i.fa.fa-minus.line-height-40
                  %input.form-control.quantity-input{type: "text"}
                  %a.input-link{href: "#"}
                    %i.fa.fa-plus.line-height-40
            %tr
              %td
                %span.in-grey-600 SubTotal
              %td
                %span.font-16.in-gold-500 €32.90
      .hidden-xs
        %table.table.table-hover
          %tr.no-hover
            %th.col-pic.pl-0
              %span.in-grey-600 Product
            %th.col-title
            %th.col-price
              %span.in-grey-600 Price
            %th.col-quantity
              %span.in-grey-600 Quantity
            %th.col-total
              %span.in-grey-600 SubTotal
            %th.col-close
          %tr
            %td
              .general-img-wrap-table
                %img.cart-img-shadow.pull-left{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
            %td
              %p.general-title Android Programming for Beginners
            %td
              %span.font-16.in-gold-500 €28.50
            %td
              .input-group
                %a.input-link{href: "#"}
                  %i.fa.fa-minus.line-height-40
                %input.form-control.quantity-input{type: "text"}
                %a.input-link{href: "#"}
                  %i.fa.fa-plus.line-height-40
            %td
              %span.font-16.in-gold-500 €32.90
            %td
              %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
                %span{'aria-hidden': "true"} &times;
          %tr
            %td
              .general-img-wrap-table
                %img.cart-img-shadow.pull-left{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
            %td
              %p.general-title Android Programming for Beginners
            %td
              %span.font-16.in-gold-500 €28.50
            %td
              .input-group
                %a.input-link{href: "#"}
                  %i.fa.fa-minus.line-height-40
                %input.form-control.quantity-input{type: "text"}
                %a.input-link{href: "#"}
                  %i.fa.fa-plus.line-height-40
            %td
              %span.font-16.in-gold-500 €32.90
            %td
              %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
                %span{'aria-hidden': "true"} &times;
      .general-order-wrap
        .row
          .col-sm-4
            .input-group.general-input-group
              %label.font-weight-light Enter Your Coupon Code
              %input.form-control.mb-30{type: "text", placeholder: "Enter Your Coupon Code "}
              %div
                %button.btn.btn-primary.mr-5.mb-15.visible-xs-inline-block Apply Coupon
                %button.btn.btn-primary.mb-15.res-block Update cart
          .col-sm-8
            .res-mr-200.text-center.general-text-right
              %p.in-gold-500.font-18 Order Summary
              %table.general-summary-table.general-summary-table-right.general-text-right
                %tr
                  %td
                    %p.font-16 Subtotal:
                  %td
                    %p.font-16 €117.69
                %tr
                  %td
                    %p.font-16 Coupon:
                  %td
                    %p.font-16 €0.00
                %tr
                  %td
                    %strong.font-18 Order Total:
                  %td
                    %strong.font-18 €117.69
              %button.btn.btn-default.mb-20.visible-xs-inline-block Checkout
      %button.btn.btn-default.mb-20.hidden-xs.center-block Checkout
    
    %script{src: "https://use.fontawesome.com/67602d7308.js"}
    %script{src: "../../javascripts/jquery.js"}
    %script{src: "../../javascripts/bootstrap.js"}

app/views/carts/show.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin Cart
  .visible-xs        
  .hidden-xs
    -if @order.line_items.empty?
      .general-order-wrap
        .row
          .col-sm-4
          %h1.general-title-margin
            Cart is empty, You can add book  
            =link_to 'here', root_path
    -else
      =simple_form_for @order, url: cart_path, method: :patch do |f|
        =render 'table', field: f
        .general-order-wrap
          .row
            .col-sm-4
              = f.simple_fields_for :coupon, @coupon_form do |coupon|
                .input-group.general-input-group
                  .mb-30
                    = coupon.input :code                
              = f.submit 'Update cart', class: 'btn btn-primary mb-15 res-block'  
            .col-sm-8
              .res-mr-200.text-center.general-text-right
                %p.in-gold-500.font-18 Order Summary
                %table.general-summary-table.general-summary-table-right.general-text-right
                  =render '/orders/order_summary'
          .text-center
            = f.submit 'checkout', name: :to_checkout, class: 'btn btn-default mb-20'