config/routes.rb
Rails.application.routes.draw do    

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    get 'fast_registrations', to: 'fast_registrations#show', as: :show_fast_registrations
    post 'fast_registrations', to: 'fast_registrations#quick_registration', as: :fast_registration

  end
    
  scope "(:locale)", locale: /en|ru/ do  
    resources :orders
    resources :carts, only: [:show, :update]
    resources :line_items
    resources :catalog, only: [:index, :show]
    resources :checkouts, only: [:show, :update]
    resources :books do
      post :create_line_item, on: :member
    end
    resource :user, only: [:edit] do 
      collection do 
        patch 'update_password'
        patch 'update_email'
      end
    end
    get '/users/:id', to: 'users#settings', as: 'settings'
    patch 'users/:id', to: 'users#update_address', as:'update_address'
    root to:"home#index"
  end


end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  include Rectify::ControllerHelpers
  before_action :get_last_url, only: [:index, :show]
  skip_before_action :clean_last_url 
  def index
    sort_books
  end

  def show
    @category = Category.find(params[:id]) if params[:id]
    sort_books
  end
  

  private

  def get_last_url
    cookies['my_previous_url'] = request.original_url
  end

  def set_sort_type
    session[:sort_type] =
      params[:sort_type] || session[:sort_type] || :title_asc
  end

  def define_current_filter_title(filter)
    @current_filter = Book::SORT_FILTERS[filter.to_sym]
  end

  def sort_books
    set_sort_type
    define_current_filter_title(session[:sort_type])
    @books = SortBooks.call(@category, session[:sort_type])
      .page(params[:page] || 1).per(8)
  end
  
   
end

app/helpers/catalog_helper.rb
module CatalogHelper

  def sort_link(column, direction, title = nil)
    title ||= column.titleize
    #direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to "#{title}".html_safe, {column: column, direction: direction}
  end
end

app/views/catalog/_catalog_list.html.haml
- @books.each do |book|
  .col-xs-6.col-sm-3
    .general-thumb-wrap
      .thumbnail.general-thumbnail
        %img.img-shadow.general-thumbnail-img{src: book.pictures[0].image_url}
        .thumb-hover
          .general-thumb-link-wrap
            %a.thumb-hover-link{href: book_path(book)}
              %i.fa.fa-eye.thumb-icon{'aria-hidden': "true"}
            =link_to create_line_item_book_path(id: book.id, book: {quantity: '1'}), method: :post, class: 'thumb-hover-link' do
              %i.fa.fa-shopping-cart.thumb-icon

    .general-thumb-info{"data-id" => book.id}
      %p.general-title 
        =truncate(book.title, length: 30)
      %p.font-16.in-gold-500 
        =number_to_currency(book.price)
      %span.divider-sm
      %p.in-grey-600.small
        =book.get_author_names

app/views/catalog/_filter_panel.html.haml
.dropdown
  %a.dropdown-toggle.dropdown-btn{class: "width-240", href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
    = @current_filter
    %i.fa.fa-angle-down.dropdown-icon
  %ul.dropdown-menu
    %li
      = link_to "A - Z", catalog_path(@category, sort_type: :title_asc)
    %li
      = link_to "Z - A", catalog_path(@category, sort_type: :title_desc)
    %li
      = link_to "Newest first", catalog_path(@category, sort_type: :newest)
    %li
      = link_to "Popular first", catalog_path(@category, sort_type: :popular)
    %li
      = link_to "Price: high to low", catalog_path(@category, sort_type: :high_price)
    %li
      = link_to "Price: low to high", catalog_path(@category, sort_type: :low_price)

app/views/catalog/index.html.haml
%main.container
  %h1.general-title-margin Сatalog
  .hidden-xs.clearfix
    .pull-right
      .dropdown
        %a.dropdown-toggle.dropdown-btn{class: "width-240", href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
          = @current_filter
          %i.fa.fa-angle-down.dropdown-icon
        %ul.dropdown-menu
          %li
            = link_to "A - Z", catalog_index_path(sort_type: :title_asc)
          %li
            = link_to "Z - A", catalog_index_path(sort_type: :title_desc)
          %li
            = link_to "Newest first", catalog_index_path(sort_type: :newest)
          %li
            = link_to "Popular first", catalog_index_path(sort_type: :popular)
          %li
            = link_to "Price: high to low", catalog_index_path(sort_type: :high_price)
          %li
            = link_to "Price: low to high", catalog_index_path(sort_type: :low_price)
            
    %ul.list-inline.pt-10.mb-25.mr-240
      %li.mr-35
        %a.filter-link{href: catalog_index_path}
          All
          %span.badge.general-badge 
            =Book.count
      - @categories.each do |category|
        %li.mr-35
          %a.filter-link{href: catalog_path(category)}
            = category.name
            %span.badge.general-badge
              = category.books_in_category
  .mb-40.visible-xs
    %p.in-grey-600.small.mb-10 Filter by category
    .dropdown.mb-20
      %a.dropdown-toggle.dropdown-btn{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
        Newest first
        %i.fa.fa-angle-down.dropdown-icon
      %ul.dropdown-menu
        %li
          %a{href: "#"} Newest first
        %li
          %a{href: "#"} Popular first
        %li
          %a{href: "#"} Price: Low to hight
        %li
          %a{href: "#"} Price: Low to hight
  .mb-120
    .row.pagination
      =render "catalog_list"
    .text-center
      = link_to_next_page  @books,'View More', remote: true, id: 'load_more_link', class: 'btn btn-primary'
  

app/views/catalog/index.js.erb
$('.row.pagination').append('<%= escape_javascript(render 'catalog_list') %>');
$('#load_more_link').replaceWith("<%= escape_javascript(link_to_next_page(@books, 'Load More', remote: true, id: 'load_more_link', class: 'btn btn-primary'))%>");

app/views/catalog/show.html.haml
%main.container
  %h1.general-title-margin Сatalog
  .hidden-xs.clearfix
    .pull-right
      = render  "filter_panel", locals: {width: 240}
    %ul.list-inline.pt-10.mb-25.mr-240
      %li.mr-35
        %a.filter-link{href: catalog_index_path}
          All
          %span.badge.general-badge 
            =Book.count
      - @categories.each do |category|
        %li.mr-35{:class => "#{"active" if @category == category}"}
          = link_to catalog_path(category, sort_type: params[:sort_type]), class: "filter-link" do
            = category.name
            %span.badge.general-badge
              = category.books_in_category
  .mb-40.visible-xs
    %p.in-grey-600.small.mb-10 Filter by category
    .dropdown.mb-20
      %a.dropdown-toggle.dropdown-btn{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
        Newest first
        %i.fa.fa-angle-down.dropdown-icon
      %ul.dropdown-menu
        %li
          %a{href: "#"} Newest first
        %li
          %a{href: "#"} Popular first
        %li
          %a{href: "#"} Price: Low to hight
        %li
          %a{href: "#"} Price: Low to hight
  .mb-120
    .row.pagination
      =render "catalog_list"
    .text-center
      = link_to_next_page  @books,'View More', remote: true, id: 'load_more_link', class: 'btn btn-primary'
  

app/views/catalog/show.js.erb
$('.row.pagination').append('<%= escape_javascript(render 'catalog_list') %>');
$('#load_more_link').replaceWith("<%= escape_javascript(link_to_next_page(@books, 'Load More', remote: true, id: 'load_more_link', class: 'btn btn-primary'))%>");