config/routes.rb
Rails.application.routes.draw do    

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    get 'fast_registrations', to: 'fast_registrations#show', as: :show_fast_registrations
    post 'fast_registrations', to: 'fast_registrations#quick_registration', as: :fast_registration

  end
    
  scope "(:locale)", locale: /en|ru/ do  
    resources :orders
    resources :carts, only: [:show, :update]
    resources :line_items
    resources :catalog, only: [:index, :show]
    resources :checkouts, only: [:show, :update]
    resources :books do
      post :create_line_item, on: :member
    end
    resource :user, only: [:edit] do 
      collection do 
        patch 'update_password'
        patch 'update_email'
      end
    end
    get '/users/:id', to: 'users#settings', as: 'settings'
    patch 'users/:id', to: 'users#update_address', as:'update_address'
    root to:"home#index"
  end


end

app/views/layouts/_footer.html.haml
%footer.navbar.navbar-inverse.mb-0
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            %a.nav-link{href: "/"} Home
          %li
            %a.nav-link{href: '#'} Shop
          %li
            %a.nav-link{href: "#"} Orders
          
      .col-sm-3
        %p.general-nav-mail support@bookstore.com
        %p.general-nav-number (555)-555-5555
        %ul.list-inline.general-align
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-facebook{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-twitter{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-google-plus{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-instagram{'aria-hidden': "true"}

app/views/layouts/_header.html.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left.ml-15{type: "button", 'data-toggle': "collapse", 'data-target': "#navbar"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand Bookstore      
    
    %a.shop-link.pull-right.hidden-xs{href: cart_path(id: session[:order_id])}
      %span.shop-icon
        -if session[:order_id]
          %span.shop-quantity 
            = @order.amount_of_books

    #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': "false"}
      .hidden-xs
        %ul.nav.navbar-nav
          %li
            = link_to t('language.en'), url_for(locale: :en)
          %li
            = link_to t('language.ru'), url_for(locale: :ru)
          %li
            %a{href: "/"} Home
          %li.dropdown
            %a.dropdown-toggle{href: '#', 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"} Shop
            %ul.dropdown-menu
              - @categories.each do |category|
                %li
                  %a{href: catalog_path(category)} 
                    = category.name
          - if user_signed_in?
            %li            
              %a.dropdown-toggle{href: '#', 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"} My account
              %ul.dropdown-menu                
                %li
                  = link_to "Orders", orders_path
                -if can? :access, :rails_admin
                  %li
                    = link_to "admin",  rails_admin_path
                %li
                  = link_to "Settings", settings_path(current_user)
                %li.divider{role: "separator"}
                %li
                  = link_to "Logout", destroy_user_session_path, method: :delete
              
          - else
            %li 
              = link_to "Log in", new_user_session_path
            %li 
              = link_to "Sign up", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    
    %title Bookstore
    %meta{name: "viewport", content: "width=device-width"}
    %link{href: "https://fonts.googleapis.com/css?family=Open+Sans:300,400,600", rel: "stylesheet"}
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    - flash.each do |type, message|
      %div{class: "alert alert-#{change_flash_class(type)}"}
        %button{type: "button", class: "close", "data-dismiss": "alert", "aria-label": "Close"}
          %span{"aria-hidden": "true"} &times;
        = message
    = yield
    = render 'layouts/footer' 
  %script{src: "https://use.fontawesome.com/67602d7308.js"}